### ISSUE TITLE
Reading and navigating

### ISSUE THREAD

**Issue by cfidler** [BNHM/ecoreader#30] opened 2016-01-07 23:06 UTC
I've had two separate users report to me that it is difficult to navigate through the section. People seem to want the best of view section and read section. One way to help would be if we added a box in the read section that said: Jump to page __ of XXX.

**Comment by mkoo** [comment] 2016-01-08 17:16
Duplicate of issue #28

**Closed as completed by mkoo** 2016-01-08 17:16 UTC
Labels: duplicate
